apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  selector:
    matchLabels:
      app: web-node
  template:
    metadata:
      labels:
        app: web-node
    spec:
      containers:
      - name: node-deployment
        image: muralisocial123/devops-web:2.0
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata:
  name: web-app-svc
spec:
  selector:
    app: web-node
  ports:
  - port: 81
    targetPort: 80
  type: ClusterIP
--- 
apiVersion: v1 
kind: Service
metadata:
  name: web-app-node-port
spec:
  selector:
    app: web-node
  ports:
  - port: 81
    targetPort: 80
  type: NodePort  