apiVersion: v1 
kind: Pod
metadata:
  name: example-gce-pod
spec:
  restartPolicy: Never
  containers:
  - name: busybox-pod
    image: busybox
    command: ['sh', '-c', 'while true; do echo DevOps Training S4..!!! >> /output/output.txt; sleep 5; done']
    volumeMounts:
      - name: my-volume
        mountPath: /output
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: example-gce-pvc
   